Fix get_text_format() method name
An error in the logs showed a deprecated method was being called;

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/sugar3/activity/activity.py", line 1277, in _prepare_close
    self.save()
    ~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/sugar3/activity/activity.py", line 978, in save
    self.write_file(file_path)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 616, in write_file
    text = page.vt.get_text(Vte.Format.TEXT)
TypeError: Callback needs to be a function or method not Format

This fixes that.